Repository ChainSafe/ChainGuardian, pull requests merged in 2021-03, with the labels that each got.

#511 Fix blank page on remote beacon node
  src/renderer/containers/BeaconNode/BeaconNodeContainer.tsx
Labels: bug

#508 Release 0.5.1
  package.json
Labels: Meta: Exclude From Changelog

#514 update storybook
  .storybook/addons.ts
  .storybook/config.ts
  .storybook/main.js
  .storybook/preview.js
  .storybook/webpack.config.js
  package.json
  yarn.lock
Labels: Meta: Exclude From Changelog, dependencies

#523 Fix "No such container" message in docker logs
  src/renderer/services/docker/container.ts
  src/renderer/services/utils/logging/buffered.ts
Labels: bug

#524 Fix add validator loader on first add
  src/renderer/containers/Onboard/Consent/ConsentContainer.tsx
  src/renderer/ducks/settings/slice.ts
Labels: bug

#522 Fix logs stop loading
  src/renderer/ducks/beacon/sagas.ts
  src/renderer/services/docker/container.ts
Labels: bug

#526 Fix Beacon Node start/stop button
  src/renderer/containers/BeaconNodes/BeaconNodeButtons.tsx
  src/renderer/ducks/beacon/sagas.ts
Labels: bug

#527 Release 0.5.3
  package.json
Labels: Meta: Exclude From Changelog

#535 Fix sentry sourcemap
  .github/workflows/release.yaml
Labels: Meta: Exclude From Changelog

#536 Teku testnet
  .env.dist
  lighthouse-testnet.yml
  src/renderer/services/eth2/networks/local.ts
  teku-testnet.yml
  testnet/teku/start.sh
  testnet/teku/vars.env
Labels: Meta: Exclude From Changelog

#541 Localnet validator testing
  integration/lighthouse-keystore.json
  integration/lighthouse.ts
  integration/restValidation.ts
  integration/teku.ts
  package.json
  src/renderer/ducks/beacon/sagas.ts
  src/renderer/ducks/validator/sagas.ts
  src/renderer/services/api/http/httpClient.ts
  src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconApi.ts
  src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconPoolApi.ts
  src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconStateApi.ts
  src/renderer/services/eth2/client/eth2ApiClient/cgEth2EventsApi.ts
  src/renderer/services/eth2/client/eth2ApiClient/index.ts
  src/renderer/services/eth2/client/interface.ts
  src/renderer/services/eth2/networks/local.ts
  testnet/lighthouse/data/boot_enr.yaml
  testnet/lighthouse/data/config.yaml
  testnet/lighthouse/data/deploy_block.txt
  testnet/lighthouse/data/genesis.ssz
  testnet/lighthouse/data/secrets/0x81283b7a20e1ca460ebd9bbd77005d557370cabb1f9a44f530c4c4c66230f675f8df8b4c2818851aa7d77a80ca5a4a5e
  testnet/lighthouse/data/secrets/0x84398f539a64cbe01cfcd8c485ea51cd6657b94df93ee9b5dc61e1f18f69da6ca9d4dba63c956a81c68d5d4d4277a60f
  testnet/lighthouse/data/secrets/0x872c61b4a7f8510ec809e5b023f5fdda2105d024c470ddbbeca4bc74e8280af0d178d749853e8f6a841083ac1b4db98f
  testnet/lighthouse/data/secrets/0x876dd4705157eb66dc71bc2e07fb151ea53e1a62a0bb980a7ce72d15f58944a8a3752d754f52f4a60dbfc7b18169f268
  testnet/lighthouse/data/secrets/0x88c141df77cd9d8d7a71a75c826c41a9c9f03c6ee1b180f3e7852f6a280099ded351b58d66e653af8e42816a4d8f532e
  testnet/lighthouse/data/secrets/0x903e2989e7442ee0a8958d020507a8bd985d3974f5e8273093be00db3935f0500e141b252bd09e3728892c7a8443863c
  testnet/lighthouse/data/secrets/0x9314c6de0386635e2799af798884c2ea09c63b9f079e572acc00b06a7faccce501ea4dfc0b1a23b8603680a5e3481327
  testnet/lighthouse/data/secrets/0x9893413c00283a3f9ed9fd9845dda1cea38228d22567f9541dccc357e54a2d6a6e204103c92564cbc05f4905ac7c493a
  testnet/lighthouse/data/secrets/0x9977f1c8b731a8d5558146bfb86caea26434f3c5878b589bf280a42c9159e700e9df0e4086296c20b011d2e78c27d373
  testnet/lighthouse/data/secrets/0xa3a32b0f8b4ddb83f1a0a853d81dd725dfe577d4f4c3db8ece52ce2b026eca84815c1a7e8e92a4de3d755733bf7e4a9b
  testnet/lighthouse/data/secrets/0xa6d310dbbfab9a22450f59993f87a4ce5db6223f3b5f1f30d2c4ec718922d400e0b3c7741de8e59960f72411a0ee10a7
  testnet/lighthouse/data/secrets/0xa8d4c7c27795a725961317ef5953a7032ed6d83739db8b0e8a72353d1b8b4439427f7efa2c89caa03cc9f28f8cbab8ac
  testnet/lighthouse/data/secrets/0xa99a76ed7796f7be22d5b7e85deeb7c5677e88e511e0b337618f8c4eb61349b4bf2d153f649f7b53359fe8b94a38e44c
  testnet/lighthouse/data/secrets/0xab0bdda0f85f842f431beaccf1250bf1fd7ba51b4100fd64364b6401fda85bb0069b3e715b58819684e7fc0b10a72a34
  testnet/lighthouse/data/secrets/0xb89bebc699769726a318c8e9971bd3171297c61aea4a6578a7a4f94b547dcba5bac16a89108b6b6a1fe3695d1a874a0b
  testnet/lighthouse/data/validators/0x81283b7a20e1ca460ebd9bbd77005d557370cabb1f9a44f530c4c4c66230f675f8df8b4c2818851aa7d77a80ca5a4a5e/voting-keystore.json
  testnet/lighthouse/data/validators/0x84398f539a64cbe01cfcd8c485ea51cd6657b94df93ee9b5dc61e1f18f69da6ca9d4dba63c956a81c68d5d4d4277a60f/voting-keystore.json
  testnet/lighthouse/data/validators/0x872c61b4a7f8510ec809e5b023f5fdda2105d024c470ddbbeca4bc74e8280af0d178d749853e8f6a841083ac1b4db98f/voting-keystore.json
  testnet/lighthouse/data/validators/0x876dd4705157eb66dc71bc2e07fb151ea53e1a62a0bb980a7ce72d15f58944a8a3752d754f52f4a60dbfc7b18169f268/voting-keystore.json
  testnet/lighthouse/data/validators/0x88c141df77cd9d8d7a71a75c826c41a9c9f03c6ee1b180f3e7852f6a280099ded351b58d66e653af8e42816a4d8f532e/voting-keystore.json
  testnet/lighthouse/data/validators/0x903e2989e7442ee0a8958d020507a8bd985d3974f5e8273093be00db3935f0500e141b252bd09e3728892c7a8443863c/voting-keystore.json
  testnet/lighthouse/data/validators/0x9314c6de0386635e2799af798884c2ea09c63b9f079e572acc00b06a7faccce501ea4dfc0b1a23b8603680a5e3481327/voting-keystore.json
  testnet/lighthouse/data/validators/0x9893413c00283a3f9ed9fd9845dda1cea38228d22567f9541dccc357e54a2d6a6e204103c92564cbc05f4905ac7c493a/voting-keystore.json
  testnet/lighthouse/data/validators/0x9977f1c8b731a8d5558146bfb86caea26434f3c5878b589bf280a42c9159e700e9df0e4086296c20b011d2e78c27d373/voting-keystore.json
  testnet/lighthouse/data/validators/0xa3a32b0f8b4ddb83f1a0a853d81dd725dfe577d4f4c3db8ece52ce2b026eca84815c1a7e8e92a4de3d755733bf7e4a9b/voting-keystore.json
  testnet/lighthouse/data/validators/0xa6d310dbbfab9a22450f59993f87a4ce5db6223f3b5f1f30d2c4ec718922d400e0b3c7741de8e59960f72411a0ee10a7/voting-keystore.json
  testnet/lighthouse/data/validators/0xa8d4c7c27795a725961317ef5953a7032ed6d83739db8b0e8a72353d1b8b4439427f7efa2c89caa03cc9f28f8cbab8ac/voting-keystore.json
  testnet/lighthouse/data/validators/0xa99a76ed7796f7be22d5b7e85deeb7c5677e88e511e0b337618f8c4eb61349b4bf2d153f649f7b53359fe8b94a38e44c/voting-keystore.json
  testnet/lighthouse/data/validators/0xab0bdda0f85f842f431beaccf1250bf1fd7ba51b4100fd64364b6401fda85bb0069b3e715b58819684e7fc0b10a72a34/voting-keystore.json
  testnet/lighthouse/data/validators/0xaec922bd7a9b7b1dc21993133b586b0c3041c1e2e04b513e862227b9d7aecaf9444222f7e78282a449622ffc6278915d/voting-keystore.json
  testnet/lighthouse/data/validators/0xb89bebc699769726a318c8e9971bd3171297c61aea4a6578a7a4f94b547dcba5bac16a89108b6b6a1fe3695d1a874a0b/voting-keystore.json
  testnet/lighthouse/setup.sh
  testnet/lighthouse/start-beacon-node.sh
  testnet/lighthouse/start-second-beacon-node.sh
  testnet/lighthouse/start-validator-client.sh
  testnet/lighthouse/vars.env
  yarn.lock
Labels: enhancement

#547 Fix modal and loader overlapping
  .github/workflows/release.yaml
  src/renderer/ducks/beacon/sagas.ts
  yarn.lock
Labels: bug

#548 Settings screem
  src/main/menu/menu.ts
  src/renderer/app.tsx
  src/renderer/assets/img/cog.svg
  src/renderer/constants/routes.ts
  src/renderer/containers/Application.tsx
  src/renderer/containers/Settings/Settings.tsx
  src/renderer/containers/Settings/settings.scss
  src/renderer/ducks/settings/actions.ts
  src/renderer/ducks/settings/sagas.ts
  src/renderer/ducks/settings/selectors.ts
  src/renderer/ducks/settings/slice.ts
  src/renderer/overlays/index.scss
  src/renderer/overlays/index.tsx
  src/renderer/services/db/api/repositories/settings.ts
  src/renderer/style/index.scss
Labels: enhancement

#549 Max docker container ram
  src/renderer/components/ConfigureBeaconNode/ConfigureBeaconNode.tsx
  src/renderer/containers/AddBeaconNode/AddBeaconNode.tsx
  src/renderer/ducks/beacon/sagas.ts
  src/renderer/services/docker/type.ts
  src/renderer/services/docker/utils.ts
  src/renderer/services/eth2/client/defaults.ts
  src/renderer/services/eth2/client/lighthouse/defaults.ts
  test/unit/services/docker/DockerCommand.spec.ts
  test/unit/services/docker/DockerRunParams.spec.ts
Labels: enhancement

#552 Track user count
  package.json
  src/main/gui/window.ts
  src/renderer/app.tsx
  src/renderer/constants/routes.ts
  src/renderer/containers/Application.tsx
  src/renderer/containers/Consent/Consent.tsx
  src/renderer/containers/Consent/consent.scss
  src/renderer/containers/Onboard/Consent/ConsentContainer.tsx
  src/renderer/containers/Onboard/CreatePassword/CreatePasswordContainer.tsx
  src/renderer/containers/Onboard/OnboardContainer.tsx
  src/renderer/containers/Settings/Settings.tsx
  src/renderer/containers/Tracking/Tracking.tsx
  src/renderer/ducks/settings/sagas.ts
  src/renderer/ducks/validator/sagas.ts
  src/renderer/models/settings.ts
  src/renderer/models/types/settings.ts
  src/renderer/services/db/api/repositories/settings.ts
  src/renderer/services/eth2/client/eth2ApiClient/cgEth2BeaconBlocksApi.ts
  src/renderer/services/tracking/index.ts
  src/renderer/style/index.scss
  yarn.lock
Labels: enhancement

#545 Teku Beacon Node
  .env.dist
  integration/lighthouse.ts
  integration/restValidation.ts
  integration/teku.ts
  src/renderer/components/ConfigureBeaconNode/ConfigureBeaconNode.tsx
  src/renderer/components/ConfigureBeaconNode/InputBeaconNode.tsx
  src/renderer/components/Dropdown/dropdown.scss
  src/renderer/containers/AddBeaconNode/AddBeaconNode.tsx
  src/renderer/containers/Validator/SlashingDBUpload.tsx
  src/renderer/containers/ValidatorDetails/ValidatorLogs.tsx
  src/renderer/ducks/beacon/sagas.ts
  src/renderer/ducks/validator/sagas.ts
  src/renderer/ducks/validator/slice.ts
  src/renderer/models/account.ts
  src/renderer/services/docker/getClientParams.ts
  src/renderer/services/eth2/client/eth2ApiClient/cgEth2EventsApi.ts
  src/renderer/services/eth2/client/eth2ApiClient/index.ts
  src/renderer/services/eth2/client/lighthouse/index.ts
  src/renderer/services/eth2/client/module.ts
  src/renderer/services/eth2/client/teku/defaults.ts
  src/renderer/services/eth2/client/teku/index.ts
  src/renderer/services/eth2/client/utils.ts
  src/renderer/services/eth2/networks/local.ts
  src/renderer/services/eth2/networks/pyrmont.ts
  src/renderer/services/utils/getValidatorStatus.ts
  src/renderer/services/utils/validator.ts
Labels: enhancement
